site_name: Blood Bowl Base
theme:
  name: material
  custom_dir: overrides
  logo: assets/BB2020_Badge.png
  favicon: assets/BB2020_Favicon.ico
  font:
    text: Roboto Slab
  features:  
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.top
extra:
  generator: false
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - tables
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/tooltip_skills.md
        - includes/tooltip_teams.md        
        - includes/tooltip_staff.md
        - includes/tooltip_starplayers.md
        - includes/tooltip_team_special_rules.md
        - includes/tooltip_inducements.md
        - includes/tooltip_new_inducements.md
nav:
  - Cheat Sheet: 'cheat_sheet.md'
  - Core Rules: 
      - 'Core Rules': 'core_rules/index.md'
      - 'Blood Bowl Stadia': 'core_rules/blood_bowl_stadia.md'
      - 'Rules and Regulations': 'core_rules/rules_and_regulations.md'
      - 'The Rules of Blood Bowl': 'core_rules/the_rules_of_blood_bowl.md'
      - 'Post-game Sequence': 'core_rules/post-game_sequence.md'
      - 'Skills and Traits': 'core_rules/skills_and_traits.md'
      - 'Inducements in Detail': 'core_rules/inducements_in_detail.md'
      - 'League and Exhibition Play': 'core_rules/league_and_exhibition_play.md'
      - 'The Teams': 'core_rules/the_teams.md'
      - 'Lastest FAQ': 'core_rules/faq_281123.md'
  - Matched Play: 
      - 'Matched Play': 'matched_play/index.md'
      - 'Guide': 'matched_play/guide.md'
  - Death Zone: 
      - 'Death Zone': 'death_zone/index.md'
      - 'New Inducements': 'death_zone/new_inducements.md'
      - 'Fabulous Freebooters': 'death_zone/fabulous_freebooters.md'
      - 'Titanic Effort.. The Biggest of the Big Guys': 'death_zone/titanic_effort.md'
      - 'Sponsorship': 'death_zone/sponsorship.md'
      - 'Blood Bowl Stadia': 'death_zone/blood_bowl_stadia.md'
      - 'A Load of Balls': 'death_zone/a_load_of_balls.md'
      - 'New Weather Tables': 'death_zone/new_weather_tables.md'
      - 'Match Events': 'death_zone/match_events.md'
      - 'Blood Bowl Sevens': 'death_zone/blood_bowl_sevens.md'
  - Dungeon Bowl: 
      - 'Dungeon Bowl': 'dungeon_bowl/index.md'
      - 'The Game of Dungeon Bowl': 'dungeon_bowl/the_game_of_dungeon_bowl.md'
      - 'Rules and Regulations': 'dungeon_bowl/rules_and_regulations.md'
      - 'Set-Up': 'dungeon_bowl/set-up.md'
      - 'The Rules of Dungeon Bowl': 'dungeon_bowl/the_rules_of_dungeon_bowl.md'
      - 'Post-game Sequence': 'dungeon_bowl/post-game_sequence.md'
      - 'Skills and Traits': 'dungeon_bowl/skills_and_traits.md'
      - 'Inducements': 'dungeon_bowl/inducements.md'
      - 'League and Exhibition Play': 'dungeon_bowl/league_and_exhibition_play.md'
      - 'The Teams': 'dungeon_bowl/the_teams.md'
  - Blitz Bowl: 
      - 'Blitz Bowl': 'blitz_bowl/index.md'
      - 'Components': 'blitz_bowl/components.md'
      - 'The Rules of Blitz Bowl': 'blitz_bowl/rules.md'
      - 'Teams': 'blitz_bowl/teams.md'
  - Gutter Bowl: 
    - 'Gutter Bowl': 'gutter_bowl/index.md'
    - 'The Rules': 'gutter_bowl/rules.md'
    - 'Gutter Bowl Leagues': 'gutter_bowl/leagues.md'    
  - Teams:
      - 'Teams': 'teams/index.md'
      - 'Amazons': 'teams/Amazons.md'
      - 'Black Orcs': 'teams/Black_Orcs.md'
      - 'Chaos Chosen': 'teams/Chaos_Chosen.md'
      - 'Chaos Dwarves': 'teams/Chaos_Dwarves.md'
      - 'Chaos Renegades': 'teams/Chaos_Renegades.md'
      - 'Dark Elves': 'teams/Dark_Elves.md'
      - 'Dwarves': 'teams/Dwarves.md'
      - 'Elven Union': 'teams/Elven_Union.md'
      - 'Gnomes': 'teams/Gnomes.md'
      - 'Goblins': 'teams/Goblins.md'
      - 'Halflings': 'teams/Halflings.md'
      - 'High Elves': 'teams/High_Elves.md'
      - 'Humans': 'teams/Humans.md'
      - 'Imperial Nobility': 'teams/Imperial_Nobility.md'
      - 'Khorne': 'teams/Khorne.md'
      - 'Lizardmen': 'teams/Lizardmen.md'
      - 'Necromantic Horror': 'teams/Necromantic_Horror.md'
      - 'Norses': 'teams/Norses.md'
      - 'Nurgle': 'teams/Nurgle.md'
      - 'Ogres': 'teams/Ogres.md'
      - 'Old World Alliance': 'teams/Old_World_Alliance.md'
      - 'Orcs': 'teams/Orcs.md'
      - 'Shambling Undeads': 'teams/Shambling_Undeads.md'
      - 'Skavens': 'teams/Skavens.md'
      - 'Snotlings': 'teams/Snotlings.md'
      - 'Tomb Kings': 'teams/Tomb_Kings.md'
      - 'Underworld Denizens': 'teams/Underworld_Denizens.md'
      - 'Vampires': 'teams/Vampires.md'
      - 'Wood Elves': 'teams/Wood_Elves.md'
  - Star Players:
      - 'Star Players': 'starplayers/index.md'
      - 'Akhorne The Squirrel': 'starplayers/Akhorne_The_Squirrel.md'
      - 'Barik Farblast': 'starplayers/Barik_Farblast.md'
      - 'Bilerot Vomitflesh': 'starplayers/Bilerot_Vomitflesh.md'
      - "Boa Kon'ssstriktr": "starplayers/Boa_Kon'ssstriktr.md"
      - 'Bomber Dribblesnot': 'starplayers/Bomber_Dribblesnot.md'
      - "Bryce 'The Slice' Cambuel": "starplayers/Bryce_'The_Slice'_Cambuel.md"
      - "'Captain' Karina Von Riesz": "starplayers/'Captain'_Karina_Von_Riesz.md"
      - 'Cindy Piewhistle': 'starplayers/Cindy_Piewhistle.md'
      - 'Count Luthor von Drakenborg': 'starplayers/Count_Luthor_von_Drakenborg.md'
      - 'Deeproot Strongbranch': 'starplayers/Deeproot_Strongbranch.md'
      - 'Dribl and Drull': 'starplayers/Dribl_and_Drull.md'
      - 'Eldril Sidewinder': 'starplayers/Eldril_Sidewinder.md'
      - 'Estelle la Veneaux': 'starplayers/Estelle_la_Veneaux.md'
      - "Frank 'n' Stein": "starplayers/Frank_'n'_Stein.md"
      - 'Fungus the Loon': 'starplayers/Fungus_the_Loon.md'
      - 'Glart Smashrip': 'starplayers/Glart_Smashrip.md'
      - 'Gloriel Summerbloom': 'starplayers/Gloriel_Summerbloom.md'
      - 'Glotl Stop': 'starplayers/Glotl_Stop.md'
      - 'Grak and Crumbleberry': 'starplayers/Grak_and_Crumbleberry.md'
      - 'Grashnak Blackhoof': 'starplayers/Grashnak_Blackhoof.md'
      - "Gretchen Wächter 'The Blood Bowl Widow'": "starplayers/Gretchen_Wächter_'The_Blood_Bowl_Widow'.md"
      - 'Griff Oberwald': 'starplayers/Griff_Oberwald.md'
      - 'Grim Ironjaw': 'starplayers/Grim_Ironjaw.md'
      - 'Grombrindal, The White Dwarf': 'starplayers/Grombrindal,_The_White_Dwarf.md'
      - 'Hakflem Skuttlespike': 'starplayers/Hakflem_Skuttlespike.md'
      - 'Helmut Wulf': 'starplayers/Helmut_Wulf.md'
      - "Ivan 'the Animal' Deathshroud": "starplayers/Ivan_'the_Animal'_Deathshroud.md"
      - 'Ivar Eriksson': 'starplayers/Ivar_Eriksson.md'
      - 'Karla Von Kill': 'starplayers/Karla_Von_Kill.md'
      - 'Kiroth Krakeneye': 'starplayers/Kiroth_Krakeneye.md'
      - 'Kreek Rustgouger': 'starplayers/Kreek_Rustgouger.md'
      - 'Lord Borak': 'starplayers/Lord_Borak.md'
      - 'Max Spleenripper': 'starplayers/Max_Spleenripper.md'
      - 'Mighty Zug': 'starplayers/Mighty_Zug.md'
      - "Morg'n Thorg": "starplayers/Morg'n_Thorg.md"
      - 'Nobbla Blackwart': 'starplayers/Nobbla_Blackwart.md'
      - 'Puggy Baconbreath': 'starplayers/Puggy_Baconbreath.md'
      - 'Ripper Blogrot': 'starplayers/Ripper_Blogrot.md'      
      - 'Rodney Roachbait': 'starplayers/Rodney_Roachbait.md'
      - 'Roxanna Darknail': 'starplayers/Roxanna_Darknail.md'
      - 'Rowana Forestfoot': 'starplayers/Rowana_Forestfoot.md'
      - 'Rumbelow Sheepskin': 'starplayers/Rumbelow_Sheepskin.md'
      - 'Scrappa Sorehead': 'starplayers/Scrappa_Sorehead.md'
      - 'Scyla Anfingrimm': 'starplayers/Scyla_Anfingrimm.md'
      - 'Skitter Stab-stab': 'starplayers/Skitter_Stab-stab.md'
      - 'Skrorg Snowpelt': 'starplayers/Skrorg_Snowpelt.md'
      - 'Skrull Halfheight': 'starplayers/Skrull_Halfheight.md'
      - 'The Black Gobbo': 'starplayers/The_Black_Gobbo.md'
      - 'The Swift Twins': 'starplayers/The_Swift_Twins.md'
      - 'Thorsson Stouthead': 'starplayers/Thorsson_Stouthead.md'
      - 'Varag Ghoul-Chewer': 'starplayers/Varag_Ghoul-Chewer.md'
      - 'Wilhelm Chaney': 'starplayers/Wilhelm_Chaney.md'
      - 'Willow Rosebark': 'starplayers/Willow_Rosebark.md'
      - 'Withergrasp Doubledrool': 'starplayers/Withergrasp_Doubledrool.md'
      - 'Zolcath the Zoat': 'starplayers/Zolcath_the_Zoat.md'
