site_name: Blood Bowl Base
theme:
  name: material
nav:
  - Cheat Sheet: 'cheat_sheet.md'
  - Core Rules: 
      - 'Blood Bowl Stadia': 'core_rules/blood_bowl_stadia.md'
      - 'Rules and Regulations': 'core_rules/rules_and_regulations.md'
      - 'The Rules of Blood Bowl': 'core_rules/the_rules_of_blood_bowl.md'
      - 'Post-game Sequence': 'core_rules/post-game_sequence.md'
      - 'Skills and Traits': 'core_rules/skills_and_traits.md'
      - 'Inducements in Detail': 'core_rules/inducements_in_detail.md'
      - 'League and Exhibition Play': 'core_rules/league_and_exhibition_play.md'
      - 'The Teams': 'core_rules/the_teams.md'
  - Teams:
      - 'Amazons': 'teams/Amazons.md'
      - 'Black Orcs': 'teams/Black_Orcs.md'
      - 'Chaos Chosen': 'teams/Chaos_Chosen.md'
      - 'Chaos Dwarves': 'teams/Chaos_Dwarves.md'
      - 'Chaos Renegades': 'teams/Chaos_Renegades.md'
      - 'Dark Elves': 'teams/Dark_Elves.md'
      - 'Dwarves': 'teams/Dwarves.md'
      - 'Elven Union': 'teams/Elven_Union.md'
      - 'Goblins': 'teams/Goblins.md'
      - 'Halflings': 'teams/Halflings.md'
      - 'High Elves': 'teams/High_Elves.md'
      - 'Humans': 'teams/Humans.md'
      - 'Imperial Nobility': 'teams/Imperial_Nobility.md'
      - 'Khorne': 'teams/Khorne.md'
      - 'Lizardmen': 'teams/Lizardmen.md'
      - 'Necromantics': 'teams/Necromantics.md'
      - 'Norses': 'teams/Norses.md'
      - 'Nurgle': 'teams/Nurgle.md'
      - 'Ogres': 'teams/Ogres.md'
      - 'Old World Alliance': 'teams/Old_World_Alliance.md'
      - 'Orcs': 'teams/Orcs.md'
      - 'Skavens': 'teams/Skavens.md'
      - 'Slanns': 'teams/Slanns.md'
      - 'Snotlings': 'teams/Snotlings.md'
      - 'Tomb Kings': 'teams/Tomb_Kings.md'
      - 'Undeads': 'teams/Undeads.md'
      - 'Underworld Denizens': 'teams/Underworld_Denizens.md'
      - 'Vampires': 'teams/Vampires.md'
      - 'Wood Elves': 'teams/Wood_Elves.md'
  - Star Players:
      - 'Akhorne The Squirrel': 'starplayers/Akhorne_The_Squirrel.md'
      - 'Barik Farblast': 'starplayers/Barik_Farblast.md'
      - 'Bilerot Vomitflesh': 'starplayers/Bilerot_Vomitflesh.md'
      - "Boa Kon'ssstriktr": "starplayers/Boa_Kon'ssstriktr.md"
      - 'Bomber Dribblesnot': 'starplayers/Bomber_Dribblesnot.md'
      - 'Brutal Blocker': 'starplayers/Brutal_Blocker.md'
      - "Bryce 'The Slice' Cambuel": "starplayers/Bryce_'The_Slice'_Cambuel.md"
      - 'Cindy Piewhistle': 'starplayers/Cindy_Piewhistle.md'
      - 'Deeproot Strongbranch': 'starplayers/Deeproot_Strongbranch.md'
      - 'Dribl and Drull': 'starplayers/Dribl_and_Drull.md'
      - 'Eldril Sidewinder': 'starplayers/Eldril_Sidewinder.md'
      - 'Estelle la Veneaux': 'starplayers/Estelle_la_Veneaux.md'
      - "Frank 'n' Stein": "starplayers/Frank_'n'_Stein.md"
      - 'Fungus the Loon': 'starplayers/Fungus_the_Loon.md'
      - 'Glart Smashrip': 'starplayers/Glart_Smashrip.md'
      - 'Gloriel Summerbloom': 'starplayers/Gloriel_Summerbloom.md'
      - 'Glotl Stop': 'starplayers/Glotl_Stop.md'
      - 'Grak and Crumbleberry': 'starplayers/Grak_and_Crumbleberry.md'
      - 'Grashnak Blackhoof': 'starplayers/Grashnak_Blackhoof.md'
      - "Gretchen Wächter 'The Blood Bowl Widow'": "starplayers/Gretchen_Wächter_'The_Blood_Bowl_Widow'.md"
      - 'Griff Oberwald': 'starplayers/Griff_Oberwald.md'
      - 'Grim Ironjaw': 'starplayers/Grim_Ironjaw.md'
      - 'Grombrindal, The White Dwarf': 'starplayers/Grombrindal,_The_White_Dwarf.md'
      - 'Guaranteed Big Guy': 'starplayers/Guaranteed_Big_Guy.md'
      - 'Hakflem Skuttlespike': 'starplayers/Hakflem_Skuttlespike.md'
      - 'Helmut Wulf': 'starplayers/Helmut_Wulf.md'
      - 'Ivar Eriksson': 'starplayers/Ivar_Eriksson.md'
      - 'Kari Coldsteel': 'starplayers/Kari_Coldsteel.md'
      - 'Karla Von Kill': 'starplayers/Karla_Von_Kill.md'
      - 'Kreek Rustgouger': 'starplayers/Kreek_Rustgouger.md'
      - 'Legendary Lineman': 'starplayers/Legendary_Lineman.md'
      - 'Lord Borak': 'starplayers/Lord_Borak.md'
      - 'Max Spleenripper': 'starplayers/Max_Spleenripper.md'
      - 'Mighty Zug': 'starplayers/Mighty_Zug.md'
      - 'Minus Superstar': 'starplayers/Minus_superstar.md'
      - "Morg'n Thorg": "starplayers/Morg'n_Thorg.md"
      - 'Nobbla Blackwart': 'starplayers/Nobbla_Blackwart.md'
      - 'Puggy Baconbreath': 'starplayers/Puggy_Baconbreath.md'
      - 'Ripper Blogrot': 'starplayers/Ripper_Blogrot.md'
      - 'Roxanna Darknail': 'starplayers/Roxanna_Darknail.md'
      - 'Rumbelow Sheepskin': 'starplayers/Rumbelow_Sheepskin.md'
      - 'Safe Provider': 'starplayers/Safe_Provider.md'
      - 'Scrappa Sorehead': 'starplayers/Scrappa_Sorehead.md'
      - 'Scyla Anfingrimm': 'starplayers/Scyla_Anfingrimm.md'
      - 'Skrorg Snowpelt': 'starplayers/Skrorg_Snowpelt.md'
      - 'Skrull Halfheight': 'starplayers/Skrull_Halfheight.md'
      - 'The Black Gobbo': 'starplayers/The_Black_Gobbo.md'
      - 'The Swift Twins': 'starplayers/The_Swift_Twins.md'
      - 'Thorsson Stouthead': 'starplayers/Thorsson_Stouthead.md'
      - 'Varag Ghoul-Chewer': 'starplayers/Varag_Ghoul-Chewer.md'
      - 'Wilhelm Chaney': 'starplayers/Wilhelm_Chaney.md'
      - 'Willow Rosebark': 'starplayers/Willow_Rosebark.md'
      - 'Withergrasp Doubledrool': 'starplayers/Withergrasp_Doubledrool.md'
      - 'Zolcath the Zoat': 'starplayers/Zolcath_the_Zoat.md'
  #- Matched Play: 'matched_play.md'
  #- Blitz Bowl: 'blitzbowl.md'
  #- Death Zone: 'death_zone.md'